---
title: "UvA-BiTS Warehouse"
author: "Bart Aelterman <bart.aelterman@inbo.be>"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# Performance optimisation

This vignette examines the performance of different computations implemented in the UvaBitsWarehouse package.

## Profiling the different UvABiTSWarehouse steps

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=7, fig.height=6, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE, cache=TRUE)
```

```{r profile}
library(UvaBitsWarehouse)
library(data.table)
library(ggplot2)
d <- profiling_L1("../data/bird_track_logs_2000L.csv", "../data/two_birds.csv")
q <- qplot(x=d$step, y=d$timing)
q + theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

After further investigation of the `validate_tracks_data` function, this turns out to be due to the fact that parsing date_times is slow.