---
title: "UvA-BiTS ETL"
author: "Bart Aelterman <bart.aelterman@inbo.be>"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

# UvA-BiTS ETL

## Intro

At the [Research Institute for Nature and Forest](http://www.inbo.be) (INBO) we are tracking birds using the [UvA-BiTS system](http://www.uva-bits.nl/) as part of the [LifeWatch project](http://www.lifewatch.inbo.be). As tracking data volume grows quicker than human observation data (what we usually work with), we were in need for a data store that contains the cleaned and enriched tracking data in a system that is optimized for querying these *large-ish* data sets. Something like a data warehouse. This R package contains code to extract the data from the UvA-BiTS virtual lab, clean and enrich it, and load it in the data warehouse.

In this vignette, you can find:

- [How to use this package](#how-to-use-this-package)
- [A description of all the fields in the output](#output-format)
- [A detailed explanation of the processing procedure](#etl-procedure)
- [Documentation about the deprecated procedure at CartoDB](#cartodb-procedure)

## How to use this package?

Install the package and load it in your R environment.

Read the data files:

```
birds <- load_bird_file("birds_filename")
tracks <- load_tracks_file("tracks_filename")
corine <- read_raster_data("corine_filename")
proj4string(corine) <- CRS("+init=epsg:3035")
```

Validate the data (for documentation, see the section [Extracting and
validating input data](#extracting-and-validating-input-data) below):

```
birds <- validate_bird_data(birds)
tracks <- validate_tracks_data(tracks)
```

Enrich the data (see the section [Enriching the data](#enriching-the-data) below)

```
dt <- enrich_data(tracks, birds, corine)
```

Load the data in a PostgreSQL database. Make sure a database exists. A table `tracking_warehouse` will be created.

```
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname="bird_tracking", host="localhost")
data2table(con, dt)
```

To add indexes to the table, perform the `CREATE INDEX` statements in [this file](../sql/create_wh_table.sql).

## Output format

Most of the output fields will be familiar as they are entirely copied from the input tables. However, a number of fields are added during the `enrich` step of the procedure. These fields are prefixed with `inbo_` to make the distinction clear. All output fields are documented in the table below:

| field number | field name | type | description |
| ------------ | ---------- | ---- | ----------- |
| 1            | project_leader | text | Project leader of the research project for which these trackers are used |
| 2            | device_info_serial | number | ID of the GPS tracker |
| 3            | bird_name  | text | Name given to individual bird by the researcher |
| 4            | ring_code | text | Code of the metal leg ring on the individual bird |
| 5            | colour_ring_code | text | Code of the coloured leg ring on the individual bird |
| 6            | species_code | text | Code for the species for which these trackers are used |
| 7            | scientific_name | text | Species name of the individual bird |
| 8            | catch_weight | number | Weight of the individual bird in grams when catched |
| 9            | sex | text | Sex of the individual bird (noted as `male` or `female`) |
| 10           | catch_location | text | Name of area where the bird was catched. Gulls are catched on nest, so this is can be considered their colony location. Harriers are catched near their nest, so this can be considered their home range for at least the first year |
| 11           | tracking_started_at | date time | UTC timestamp for when tracking is (considered) operational (= somewhat later than tagging). Used to exclude pre-tracking test records during import |
| 12           | tracking_ended_at | date time | UTC timestamp for when tracking is no longer (considered) operational |
| 13           | is_active | boolean | `FALSE` if individual bird is confirmed or likely dead, or if we assume tracker is no longer active |
| 14           | remarks | text | Remarks by the researcher regarding the tracker or bird |
| 15           | colony_latitude | number | WGS84 latitude of the estimated catch position |
| 16           | colony_longitude | number | WGS84 longitude of the estimated catch position |
| 17           | date_time | date time | Date and time in format "yyyy-mm-dd hh:mm:ss" |
| 18           | latitude | number | latitude in WGS84 |
| 19           | longitude | number | longitude in WGS84 |
| 20           | altitude | number | Altitude in meters above sea level recorded by the GPS tracker |
| 21           | pressure | number | Pressure measured by GPS tag sensor in Pascals |
| 22           | temperature | number | Temperature recorded by the GPS tracker in degrees Celsius |
| 23           | satellites_used | number | Number of satellites used to get a GPS fix |
| 24           | gps_fixtime | number | Time to get a GPS fix in seconds |
| 25           | positiondop | number | Positional DOP (Dilution of Precision), unitless |
| 26           | h_accuracy | number | Horizontal accuracy in meters |
| 27           | v_accuracy | number | Vertical accuracy in meters |
| 28           | x_speed | number | speed in the x dimension measured by the accelerometer in meters per second |
| 29           | y_speed | number | speed in the x dimension measured by the accelerometer in meters per second |
| 30           | z_speed | number | speed in the x dimension measured by the accelerometer in meters per second |
| 31           | speed_accuracy | number | accuracy of the speed measurement |
| 32           | userflag | number | Acceptable = 0; Data flagged as unacceptable by user if not equal to 0 |
| 33           | speed_3d | number | sqrt(d.x_speed^2 + d.y_speed^2 + d.z_speed^2), m/s |
| 34           | speed_2d | number | Speed on 2D, m/s |
| 35           | direction | number | Heading in degrees (0 is north, 90 is east). |
| 36           | altitude_agl | number | Reported GPS altitude MINUS terrain elevation on the coordinate based on Digital Elevation Model data used in the e-ecology database |
| 37           | calc_year | number | Year from the date_time (column 17) field |
| 38           | calc_month | number | Month from the date_time (column 17) field |
| 39           | calc_hour | number | Hour from the date_time (column 17) field |
| 40           | calc_time_diff | number | Time (in seconds) since the birds last GPS fix |
| 41           | calc_distance_diff | number | Distance (in meters) from the birds last GPS fix |
| 42           | calc_speed_2d | number | Average two dimensional speed (in meters per seconds) of the bird between the last GPS fix and the current fix |
| 43           | calc_distance_to_colony | number | Distance (in meters) to the colony (indicated by colony_latitude and colony_longitude) |
| 44           | calc_sunlight | boolean | `TRUE` if sunlight was available at the given time and location |
| 45           | calc_outlier | boolean | `TRUE` if according to [this set of rules](#8-flag-outliers) the record is considered an outlier and should be removed from the analysis |
| 46           | calc_corine_value | text | Value of the Corine land use map at the position of the bird |


## ETL procedure

### Extracting and validating input data

The data is loaded from csv files. The following input files are expected:

#### Birds metadata

Contains information about the tracked individuals. At the INBO, this file is managed on Google Drive and it is documented [here](https://github.com/LifeWatchINBO/bird-tracking/tree/master/cartodb#bird_tracking-table).

The extraction procedure reads the bird metadata file and verifies whether all columns have the expected data types. Missing values are allowed, but values with an incorrect data type will cause the extraction to halt.

The columns `sex` and `species` are only allowed to have values defined in the package data elements `sex_choices` and `species_choices`. (Load them with `data(sex_choices)` and `data(species_choices)` to see them)

#### Tracking data

The tracking data is a dump from the UvA-BiTS virtual lab in csv format. It contains the following columns:

| field name | type | description |
| ---------- | ---- | ----------- |
| device_info_serial | number | ID of the GPS tracker |
| date_time | text | Date and time in format "yyyy-mm-dd hh:mm:ss" |
| latitude | number | latitude in WGS84 |
| longitude | number | longitude in WGS84 |
| altitude | number | Altitude in meters above sea level recorded by the GPS tracker |
| pressure | number | Pressure measured by GPS tag sensor in Pascals |
| temperature | number | Temperature recorded by the GPS tracker in degrees Celsius |
| satellites_used | number | Number of satellites used to get a GPS fix |
| gps_fixtime | number | Time to get a GPS fix in seconds |
| positiondop | number | Positional DOP (Dilution of Precision), unitless |
| h_accuracy | number | Horizontal accuracy in meters |
| v_accuracy | number | Vertical accuracy in meters |
| x_speed | number | speed in the x dimension measured by the accelerometer in meters per second |
| y_speed | number | speed in the x dimension measured by the accelerometer in meters per second |
| z_speed | number | speed in the x dimension measured by the accelerometer in meters per second |
| speed_accuracy | number | accuracy of the speed measurement |
| location | text | postgreSQL geometry; to allow GIS operations |
| userflag | number | Acceptable = 0; Data flagged as unacceptable by user if not equal to 0 |
| speed_3d | number | sqrt(d.x_speed^2 + d.y_speed^2 + d.z_speed^2), m/s |
| speed_2d | number | Speed on 2D, m/s |
| direction | number | Heading in degrees (0 is north, 90 is east). |
| altitude_agl | number | Reported GPS altitude MINUS terrain elevation on the coordinate based on Digital Elevation Model data used in the e-ecology database |

### Enriching the data

#### 1. Drop unused columns

This is actually already done while extracting the data. The `location` column is deleted from the tracking data.

#### 2. Join bird tracks with bird metadata

Based on the `device_info_serial` field, the bird metadata is attached to every tracking record. If a record in the tracking data is fond for which no bird record exists, the procedure stops. On the other hand, birds that have no tracking records are ignored.

#### 3. Delete test records

Records are deleted if the `date_time` recorded by the tracker is before the `tracking_started_at` of the bird.

#### 4. Calculate time_since_previous_fix

For every bird, the time since the previous GPS fix is calculated. The first fix of every bird gets a value `NA`. The output field is called `calc_time_diff` and is stored in seconds.

#### 5. Calculate distance travelled

The distance travelled since the last GPS fix is calculated using R's `geosphere` package. The function used is `distCosine` which performs a great circle distance computation. This new field is called `calc_distance_diff` and is expressed in meters.

#### 6. Calculate speed

Based on the calculated `calc_time_diff` and `calc_distance_diff` fields, the two dimensional speed of the bird is calculated in meters per second. The new field is called `calc_speed_2d`. 

#### 7. Calculate distance to colony

Based on the `colony_latitude` and `colony_longitude`, the distance from the GPS to the colony is computed using `geosphere`'s `distCosine` function. The new field is called `calc_dist_to_colony` and the distance is stored in meters.

#### 8. Flag outliers

If a record:

* has a `date_time` that is in the future
* has a `altitude` higher than 10.000m (10km)
* has a `calc_speed_2d` higher than 33.333 m/s (~120km/h) or below 0.
* has a horizontal accuracy (`h_accuracy`) higher than 1000m

it is flagged as outlier. This means that the new `outlier` field is set to `TRUE`.

#### 9. Link with Corine land use

To investigate the habitat use, the [Corine land cover](http://www.eea.europa.eu/data-and-maps/data/corine-land-cover-2006-raster-3) category is matched with the birds position. The new field is called `calc_corine_value` and represents the value of the matched category in the Corine dataset.

## CartoDB procedure

This ETL procedure replaces the previous import procedure used for loading into CartoDB. That procedure is documented at [github](https://github.com/LifeWatchINBO/bird-tracking/blob/master/cartodb/import-procedure.md). However, the following steps of the CartoDB import procedure are not covered by the current ETL procedure:

> <p>9. Optionally, check tracking days to discover birds with relatively low number of tracking days (could indicate bird is dead)</p>


